### ISSUE TITLE
mistake in tac description

### ISSUE THREAD

**Issue by SpikePy** [learnbyexample/cli_text_processing_coreutils#1]
> Tools like grep and sed have features to easily match the first occurrence, so applying tac on the input helps to reverse the condition from last match to first match

Isn't it the other way around?

**Comment by learnbyexample** [comment]
Yeah, I think I need to rewrite that sentence.

Without applying `tac`, the task is about matching the last occurrence. After applying `tac`, the task changes to matching the first occurrence. This is what I intended to convey, but I can now see how it can be interpreted the other way.

**Comment by learnbyexample** [comment]
Description changed in version 2.0.
